module EnvelopeTemp where

addEnvelope :: String -> String -> String
addEnvelope name code = concat [
        ".assembly extern mscorlib\n",
        "{\n",
        "  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )\n",
        "  .ver 4:0:0:0\n",
        "}\n",
        ".assembly ",
        name,
        "\n",
        "{\n",
        "  .custom instance void [mscorlib]System.Runtime.CompilerServices.CompilationRelaxationsAttribute::.ctor(int32) = ( 01 00 08 00 00 00 00 00 ) \n",
        "  .custom instance void [mscorlib]System.Runtime.CompilerServices.RuntimeCompatibilityAttribute::.ctor() = ( 01 00 01 00 54 02 16 57 72 61 70 4E 6F 6E 45 78\n",
        "                                                                                                             63 65 70 74 69 6F 6E 54 68 72 6F 77 73 01 )\n",
        "\n",
        "  // --- The following custom attribute is added automatically, do not uncomment -------\n",
        "  //  .custom instance void [mscorlib]System.Diagnostics.DebuggableAttribute::.ctor(valuetype [mscorlib]System.Diagnostics.DebuggableAttribute/DebuggingModes) = ( 01 00 07 01 00 00 00 00 )\n",
        "\n",
        "  .hash algorithm 0x00008004\n",
        "  .ver 0:0:0:0\n",
        "}\n",
        ".module ",
        name,
        ".exe\n",
        ".custom instance void System.Runtime.CompilerServices.RefSafetyRulesAttribute::.ctor(int32) = ( 01 00 0B 00 00 00 00 00 ) \n",
        ".imagebase 0x00400000\n",
        ".file alignment 0x00000200\n",
        ".stackreserve 0x00100000\n",
        ".subsystem 0x0003\n",
        ".corflags 0x00000001\n",
        ".class private auto ansi sealed beforefieldinit Microsoft.CodeAnalysis.EmbeddedAttribute\n",
        "       extends [mscorlib]System.Attribute\n",
        "{\n",
        "  .custom instance void [mscorlib]System.Runtime.CompilerServices.CompilerGeneratedAttribute::.ctor() = ( 01 00 00 00 ) \n",
        "  .custom instance void Microsoft.CodeAnalysis.EmbeddedAttribute::.ctor() = ( 01 00 00 00 ) \n",
        "  .method public hidebysig specialname rtspecialname \n",
        "          instance void  .ctor() cil managed\n",
        "  {\n",
        "    .maxstack  8\n",
        "    IL_0000:  ldarg.0\n",
        "    IL_0001:  call       instance void [mscorlib]System.Attribute::.ctor()\n",
        "    IL_0006:  nop\n",
        "    IL_0007:  ret\n",
        "  }\n",
        "}\n",
        ".class private auto ansi sealed beforefieldinit System.Runtime.CompilerServices.RefSafetyRulesAttribute\n",
        "       extends [mscorlib]System.Attribute\n",
        "{\n",
        "  .custom instance void [mscorlib]System.Runtime.CompilerServices.CompilerGeneratedAttribute::.ctor() = ( 01 00 00 00 ) \n",
        "  .custom instance void Microsoft.CodeAnalysis.EmbeddedAttribute::.ctor() = ( 01 00 00 00 ) \n",
        "  .custom instance void [mscorlib]System.AttributeUsageAttribute::.ctor(valuetype [mscorlib]System.AttributeTargets) = ( 01 00 02 00 00 00 02 00 54 02 0D 41 6C 6C 6F 77\n",
        "                                                                                                                         4D 75 6C 74 69 70 6C 65 00 54 02 09 49 6E 68 65\n",
        "                                                                                                                         72 69 74 65 64 00 )\n",
        "  .field public initonly int32 Version\n",
        "  .method public hidebysig specialname rtspecialname \n",
        "          instance void  .ctor(int32 A_1) cil managed\n",
        "  {\n",
        "    .maxstack  8\n",
        "    IL_0000:  ldarg.0\n",
        "    IL_0001:  call       instance void [mscorlib]System.Attribute::.ctor()\n",
        "    IL_0006:  nop\n",
        "    IL_0007:  ldarg.0\n",
        "    IL_0008:  ldarg.1\n",
        "    IL_0009:  stfld      int32 System.Runtime.CompilerServices.RefSafetyRulesAttribute::Version\n",
        "    IL_000e:  ret\n",
        "  }\n",
        "\n",
        "}\n",
        "\n",
        ".class private auto ansi beforefieldinit ",
        name,
        "\n",
        "       extends [mscorlib]System.Object\n",
        "{\n",
        "  .method private hidebysig static void  Main(string[] args) cil managed\n",
        "  {\n",
        "    .entrypoint\n",
        code,
        "\n",
        "}\n",
        "  .method public hidebysig specialname rtspecialname \n",
        "          instance void  .ctor() cil managed\n",
        "  {\n",
        "    .maxstack  8\n",
        "    IL_0000:  ldarg.0\n",
        "    IL_0001:  call       instance void [mscorlib]System.Object::.ctor()\n",
        "    IL_0006:  nop\n",
        "    IL_0007:  ret\n",
        "  }\n",
        "}"
    ]





